### ISSUE TITLE
Service limit

### ISSUE THREAD

**Issue by shashank2086** [electricbubble/gidevice-cli#10]
Some times i am getting these error:-

2021/07/13 20:17:41 receive packet: ServiceLimit

or

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x728275]

goroutine 24 [running]:
github.com/electricbubble/gidevice/pkg/libimobiledevice.(*dtxMessageClient).startReceive.func1(0xc00037a3c0)
        /home/runner/go/pkg/mod/github.com/electricbubble/gidevice@v0.3.2/pkg/libimobiledevice/client_dtxmessage.go:323 +0x35
created by github.com/electricbubble/gidevice/pkg/libimobiledevice.(*dtxMessageClient).startReceive
        /home/runner/go/pkg/mod/github.com/electricbubble/gidevice@v0.3.2/pkg/libimobiledevice/client_dtxmessage.go:320 +0x46

**Comment by electricbubble** [comment]
🤔 When using the `xctest` command?
