### ISSUE TITLE
mount crash

### ISSUE THREAD

**Issue by prife** [electricbubble/gidevice-cli#2]
```
$ ./gidevice-cli mount ../tmp/14.0/DeveloperDiskImage.dmg ../tmp/14.0/DeveloperDiskImage.dmg.signature
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/electricbubble/gidevice-cli/cmd.glob..func6(0x174db60, 0xc00005c640, 0x2, 0x2)
	/Users/prife/workplace/iOS/gidevice-cli/cmd/mount.go:59 +0x9c5
github.com/spf13/cobra.(*Command).execute(0x174db60, 0xc00005c5e0, 0x2, 0x2, 0x174db60, 0xc00005c5e0)
	/Users/prife/workplace/iOS/gidevice-cli/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x174dde0, 0x10014d0, 0x0, 0x0)
	/Users/prife/workplace/iOS/gidevice-cli/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/prife/workplace/iOS/gidevice-cli/vendor/github.com/spf13/cobra/command.go:897
github.com/electricbubble/gidevice-cli/cmd.Execute()
	/Users/prife/workplace/iOS/gidevice-cli/cmd/root.go:26 +0x2d
main.main()
	/Users/prife/workplace/iOS/gidevice-cli/main.go:8 +0x25
FAIL: 2
```

mount.go

```
59: dmgPath, signaturePath = args[1], args[2]
```
should be

```
dmgPath, signaturePath = args[0], args[1]
```

**Comment by electricbubble** [comment]
😂Sorry, I didn't do enough testing on this project

[v0.0.4](https://github.com/electricbubble/gidevice-cli/releases)  fixed it
